<?php


namespace Tests\Feature;

use App\Enums\TypeBanner;
use App\Models\Banner;
use App\Models\Coupon;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class BannersTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 진행중인_목록을_조회할_수_있다()
    {
        $includeBanners = Banner::factory()->count(5)->create([
            'started_at' => Carbon::now()->subDay(),
            'finished_at' => Carbon::now()->addDay(),
        ]);

        $excludeBanners = Banner::factory()->count(3)->create([
            'started_at' => Carbon::now()->addDays(1),
            'finished_at' => Carbon::now()->addDays(2),
        ]);

        $items = $this->json('get', '/api/banners')->decodeResponseJson()['data'];

        $this->assertEquals(count($includeBanners), count($items));
    }

    /** @test */
    public function 타입별_목록을_조회할_수_있다()
    {
        $includeBanners = Banner::factory()->count(5)->create([
            'type' => TypeBanner::PRODUCT,
            'started_at' => Carbon::now()->subDay(),
            'finished_at' => Carbon::now()->addDay(),
        ]);

        $excludeBanners = Banner::factory()->count(3)->create([
            'type' => TypeBanner::FARM_STORY,
            'started_at' => Carbon::now()->addDays(1),
            'finished_at' => Carbon::now()->addDays(2),
        ]);

        $items = $this->json('get', '/api/banners', [
            'type' => TypeBanner::PRODUCT
        ])->decodeResponseJson()['data'];

        $this->assertEquals(count($includeBanners), count($items));
    }
}
