<?php

namespace Tests\Feature;

use App\Models\Card;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CardsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 사용자는_자신의_목록을_조회할_수_있다()
    {
        $myCards = Card::factory()->count(3)->create([
            'user_id' => $this->user->id,
        ]);

        $otherCards = Card::factory()->count(2)->create([
           'user_id' => $this->other->id,
        ]);

        $items = $this->json('get', '/api/cards')->decodeResponseJson()['data'];

        $this->assertEquals(count($myCards), count($items));
    }

    /** @test */
    public function 사용자는_카드를_생성할_수_있다()
    {

    }

    /** @test */
    public function 사용자는_카드를_삭제할_수_있다()
    {

    }
}
