<?php



use App\Enums\TypeBanner;
use App\Models\Banner;
use App\Models\Coupon;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CommentsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 누구나_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 특정_대상에_대한_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 좋아여순으로_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 등록순으로_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 사용자는_데이터를_생성할_수_잇다()
    {
        /*commentable_id
        commentable_type
        description*/
    }

    /** @test */
    public function 사용자는_자신의_데이터를_수정할_수_있다()
    {

    }

    /** @test */
    public function 사용자는_자신의_데이터를_삭제할_수_있다()
    {

    }
}
