<?php


use App\Enums\MomentCouponGroup;
use App\Enums\TargetCouponGroup;
use App\Enums\TypeCouponGroup;
use App\Enums\TypeDiscount;
use App\Enums\TypeExpire;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CouponsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 쿠폰그룹고유번호들로_쿠폰을_생성할_수_있다()
    {

    }

    /** @test */
    public function 권한이_없는_쿠폰은_생성할_수_없다()
    {
        /*# 불가
        - moment가 있는 경우
        - 이미 보유*/
    }
}
