<?php


use App\Models\Count;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class DeliveriesTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 사용자는_자신의_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 데이터를_생성할_수_있다()
    {

    }

    /** @test */
    public function 데이터를_수정할_수_있다()
    {

    }

    /** @test */
    public function 데이터를_삭제할_수_있다()
    {

    }

    /** @test */
    public function 데이터가_기본배송지로_수정되면_다른_배송지는_기본배송지가_아니게된다()
    {

    }

}
