<?php


namespace Tests\Feature;

use App\Enums\TypeBanner;
use App\Models\Banner;
use App\Models\Coupon;
use App\Models\Estimate;
use App\Models\Program;
use App\Models\User;
use App\Models\Waiting;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class EstimatesTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 누구나_견적서를_생성할_수_있다()
    {
        $form = [
            'email' => '123@naver.com',
            'name' => '123',
            'contact' => '123',
            'title' => '123',
            'description' => '123',
            'count' => '123',
            'budget' => '123',
        ];

        $this->json('post', '/api/estimates', $form)->assertStatus(200);

        $this->assertEquals(1, Estimate::count());
    }

}
