<?php


use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class FarmStoriesTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 누구나_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 검색어로_목록을_조회할_수_있다()
    {
        // word
    }

    /** @test */
    public function 좋아요순으로_목록을_조회할_수_있다 ()
    {
        /*order_by
	count_like
	created_at*/
    }

    /** @test */
    public function 등록순으로_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 태그들을_포함한_목록을_조회할_수_있다()
    {
        // tags
    }

    /** @test */
    public function 농가별_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 특정_농가를_제외한_목록을_조회할_수_있다()
    {
        // exclude_factory_id
    }



    /** @test */
    public function 데이터를_조회할_수_있다()
    {

    }

    /** @test */
    public function 데이터를_조회하면_조회수가_갱신된다()
    {

    }

    /** @test */
    public function 데이터에서_좋아요여부를_조회할_수_있다()
    {

    }

}
