<?php



use App\Enums\TypeBanner;
use App\Enums\TypeTag;
use App\Models\Banner;
use App\Models\Coupon;
use App\Models\Tag;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class GradesTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 누구나_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 다음_등급_레벨업을_위해_남은_금액과_회차를_알_수_있다()
    {
        $includeBanners = Banner::factory()->count(5)->create([
            'started_at' => Carbon::now()->subDay(),
            'finished_at' => Carbon::now()->addDay(),
        ]);

        $excludeBanners = Banner::factory()->count(3)->create([
            'started_at' => Carbon::now()->addDays(1),
            'finished_at' => Carbon::now()->addDays(2),
        ]);

        $items = $this->json('get', '/api/banners')->decodeResponseJson()['data'];

        $this->assertEquals(count($includeBanners), count($items));
    }
}
