<?php



use App\Enums\TypeBanner;
use App\Enums\TypeTag;
use App\Models\Banner;
use App\Models\Coupon;
use App\Models\Grade;
use App\Models\Tag;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class GradesTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 누구나_목록을_조회할_수_있다()
    {
        $grades = Grade::factory()->count(10)->create();

        $items = $this->json('get', '/api/grades', [
            ''
        ])->decodeResponseJson()['data'];

        $this->assertEquals(count($grades), count($items));
    }
}
