<?php



use App\Models\Banner;
use App\Models\Coupon;
use App\Models\Program;
use App\Models\User;
use App\Models\Waiting;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class IntrosTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 누구나_사용여부_참인_목록을_조회할_수_있다()
    {
        $intros = \App\Models\Intro::factory()->count(3)->create(['use' => 1]);
        $notUseIntros = \App\Models\Intro::factory()->count(3)->create(['use' => 0]);

        $items = $this->json('get', '/api/intros', [])->decodeResponseJson()['data'];

        $this->assertEquals(count($intros), count($items));
    }

    /** @test */
    public function 사용여부가_참으로_수정되면_다른_목록은_거짓으로_수정된다()
    {
        $intros = \App\Models\Intro::factory()->count(3)->create(['use' => 1]);
        $notUseIntros = \App\Models\Intro::factory()->count(5)->create(['use' => 0]);

        $notUseIntros->first()->update(['use' => 1]);

        $this->assertEquals(\App\Models\Intro::where('use', 1)->count(), 1);
    }
}
