<?php


use App\Models\Package;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PackagesTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 이번_회차_꾸러미를_조회할_수_있다()
    {
        // 도착예정일 기준 4일 전 16시 ~ 도착 예정일 2일 전 9시까지에 있는 꾸러미
        /*- 도착예정일이 현재 이후인 애들 빠른순 cursor로 부르기
        - 반복문 돌면서 도착예정일 기준 4일 전 ~ 2일전 조건에 현재 날짜가 있는지 확인하기
        - 있다면 걔를 리턴하기*/
        $passPackage = Package::factory()->create([
            'will_delivery_at' => Carbon::now()->addDays(1),
        ]);

        $currentPackage = Package::factory()->create([
            'will_delivery_at' => Carbon::now()->addDays(3),
        ]);

        $item = $this->json('get', '/api/packages/current')->decodeResponseJson()['data'];

        $this->assertEquals($currentPackage->id, $item['id']);

    }
}
