<?php



use App\Enums\TypeBanner;
use App\Enums\TypeTag;
use App\Models\Banner;
use App\Models\Coupon;
use App\Models\Tag;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PointsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 유효기간만료처리를_실행하면_유효기간이_만료된_포인트들은_회수되고_포인트내역이_생성된다()
    {

    }
}
