<?php



use App\Enums\TypeBanner;
use App\Enums\TypeTag;
use App\Models\Banner;
use App\Models\Coupon;
use App\Models\PointHistory;
use App\Models\Tag;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PointHistoriesTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 나의_목록을_조회할_수_있다()
    {
        $myModels = PointHistory::factory()->count(3)->create([
            'user_id' => $this->user->id,
        ]);

        $otherModels = PointHistory::factory()->count(2)->create([
            'user_id' => $this->other->id,
        ]);

        $items = $this->json('get', '/api/pointHistories')->decodeResponseJson()['data'];

        $this->assertEquals(count($myModels), count($items));
    }
}
