<?php


use App\Models\Count;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PresetProductsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 쿠폰을_적용할_수_있다()
    {

    }
    /** @test */
    public function 자신의_쿠폰이고_사용한적_없는_쿠폰만_사용할_수_있다()
    {

    }

    /** @test */
    public function 쿠폰사용불가_상품에는_쿠폰을_적용할_수_없다()
    {

    }
    /** @test */
    public function 쿠폰을_적용하면_상품조합의_비용과_출고의_쿠폰적용금액이_갱신된다()
    {

    }
}
