<?php


use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ProductsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 누구나_진행중인_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 검색어로_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 태그들을_포함하는_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 생성순으로_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 리뷰수순으로_목록을_조회할_수_있다()
    {

    }

    /** @test */
    public function 주문수순으로_목록을_조회할_수_있다()
    {

    }
}
