<?php



use App\Models\Banner;
use App\Models\Coupon;
use App\Models\Product;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ReviewsTest extends TestCase
{
    use RefreshDatabase;

    protected $user;

    protected $other;

    protected $form;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
        $this->other = User::factory()->create();

        $this->actingAs($this->user);

        $this->form = [

        ];
    }

    /** @test */
    public function 누구나_목록을_조회할_수_있다()
    {
        $reviews = \App\Models\Review::factory()->count(5)->create();

        $items = $this->json('get', '/api/reviews', [

        ])->decodeResponseJson()['data'];

        $this->assertEquals(count($reviews), count($items));
    }

    /** @test */
    public function 사용자별_목록을_조회할_수_있다()
    {
        $reviews = \App\Models\Review::factory()->count(5)->create([
            'user_id' => $this->user->id,
        ]);

        $otherReviews = \App\Models\Review::factory()->count(3)->create([
            'user_id' => $this->other->id,
        ]);

        $items = $this->json('get', '/api/reviews', [
            'user_id' => $this->other->id,
        ])->decodeResponseJson()['data'];

        $this->assertEquals(count($otherReviews), count($items));
    }

    /** @test */
    public function 상품별_목록을_조회할_수_있다()
    {
        $a = \App\Models\Product::factory()->create();
        $b = \App\Models\Product::factory()->create();
        $aReviews = \App\Models\Review::factory()->count(5)->create([
            'product_id' => $a->id,
        ]);

        $bReviews = \App\Models\Review::factory()->count(3)->create([
            'product_id' => $b->id,
        ]);

        $items = $this->json('get', '/api/reviews', [
            'product_id' => $a->id,
        ])->decodeResponseJson()['data'];

        $this->assertEquals(count($aReviews), count($items));
    }

    /** @test */
    public function 사진첨부여부가_참인_목록만_조회할_수_있다()
    {
        $photoReviews = \App\Models\Review::factory()->count(5)->create([
            'photo' => 1,
        ]);

        $notPhotoReviews = \App\Models\Review::factory()->count(3)->create([
            'photo' => 0,
        ]);

        $items = $this->json('get', '/api/reviews', [
            'photo' => 1,
        ])->decodeResponseJson()['data'];

        $this->assertEquals(count($photoReviews), count($items));
    }

    /** @test */
    public function 베스트순_목록을_조회할_수_있다()
    {
        $firstItem = \App\Models\Review::factory()->create([
            'best' => 1
        ]);

        $thirdItem = \App\Models\Review::factory()->create([
            'best' => 0
        ]);

        $secondItem = \App\Models\Review::factory()->create([
            'best' => 1
        ]);

        $items = $this->json('get', '/api/reviews', [
            'order_by' => 'best',
        ])->decodeResponseJson()['data'];

        $prevItem = null;

        foreach($items as $item){
            if($prevItem)
                $this->assertTrue($prevItem['best'] >= $item['best']);

            $prevItem = $item;
        }
    }

    /** @test */
    public function 최신순_목록을_조회할_수_있다()
    {
        $firstItem = \App\Models\Review::factory()->create([
            'created_at' => Carbon::now()->addDays(0)
        ]);

        $thirdItem = \App\Models\Review::factory()->create([
            'created_at' => Carbon::now()->addDays(3)
        ]);

        $secondItem = \App\Models\Review::factory()->create([
            'created_at' => Carbon::now()->addDays(2)
        ]);

        $items = $this->json('get', '/api/reviews', [
            'order_by' => 'created_at',
        ])->decodeResponseJson()['data'];

        $prevItem = null;

        foreach($items as $item){
            if($prevItem)
                $this->assertTrue($prevItem['format_created_at'] > $item['format_created_at']);

            $prevItem = $item;
        }
    }



    /** @test */
    public function 사진을_첨부해서_생성했다면_사진첨부여부가_참이_된다()
    {
        $preset = \App\Models\Preset::factory()->create([
            'user_id' => $this->user->id,
        ]);

        $presetProduct = \App\Models\PresetProduct::factory()->create([
            'preset_id' => $preset->id,
            'state' => \App\Enums\StatePresetProduct::CONFIRMED,
            'product_id' => Product::factory()->create()->id,
        ]);

        $this->form = [
            'preset_product_id' => $presetProduct->id,
            'description' => 'asdsad',
            'score' => 5,
            'imgs' => [
                ['file' => \Illuminate\Http\UploadedFile::fake()->image('image1.jpg')],
                ['file' => \Illuminate\Http\UploadedFile::fake()->image('image2.jpg')],
            ]
        ];

        $item = $this->json('post', '/api/reviews', $this->form)->decodeResponseJson()['data'];

        $this->assertEquals(1, $item['photo']);
    }

    /** @test */
    public function 수정할_수_있다()
    {
        $review = \App\Models\Review::factory()->create([
            'user_id' => $this->user->id,
        ]);

        $test = '5';

        $this->form = [
            'description' => $test,
            'score' => 5,
        ];

        $item = $this->json('patch', '/api/reviews/'.$review->id, $this->form)->decodeResponseJson()['data'];

        $this->assertEquals($item['description'], $test);
    }

    /** @test */
    public function 수정시_사진존재여부에_따라_사진첨부여부가_결정된다()
    {
        $review = \App\Models\Review::factory()->create([
            'user_id' => $this->user->id,
            'photo' => 0,
        ]);

        $this->form = [
            'description' => "123",
            'score' => 5,
            "imgs" => [
                ['file' => \Illuminate\Http\UploadedFile::fake()->image('213.jpg')],
            ]
        ];

        $item = $this->json('patch', '/api/reviews/'.$review->id, $this->form)->decodeResponseJson()['data'];

        $this->assertEquals($item['photo'], 1);

        $medias = $review->getMedia('imgs');

        $removeImgIds = [];

        foreach($medias as $media){
            $removeImgIds[] = $media->id;
        }

        $this->form = [
            'description' => "123",
            'score' => 5,
            "imgs_remove_ids" => $removeImgIds
        ];

        $item = $this->json('patch', '/api/reviews/'.$review->id, $this->form)->decodeResponseJson()['data'];

        $this->assertEquals($item['photo'], 0);
    }

    /** @test */
    public function 삭제할_수_있다()
    {
        $review = \App\Models\Review::factory()->create([
            'user_id' => $this->user->id,
            'photo' => 0,
        ]);

        $item = $this->json('delete', '/api/reviews/'.$review->id, $this->form)->assertStatus(200);
    }
}
