<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Card extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected $colors = [

    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Card $card) {
            $card->color = $card->getRandomColor();
        });
    }

    public function getRandomColor()
    {
        $color = $this->colors[rand(0, count($this->colors))];

        $user = User::withTrashed()->find($this->user_id);

        $card = $user->cards()->where('color', $color)->first();

        if($card)
            return $this->getRandColor();

        return $color;
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
