<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Card extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected $colors = [
        '#2F7A28', '#4A9B3B', '#1E5F1C', '#5CAB4D', '#74C063',
        '#287F24', '#3E9134', '#A2D38A', '#529F41', '#62B454',
        '#85C977', '#1A4D16', '#58A648', '#397B32', '#96D080',
        '#3D8A2F', '#4E9C40', '#6CB85A', '#7FCA6E', '#5DA24D',
        '#80B98A', '#B8E2A7', '#67B255', '#92D07E', '#99D88B',
        '#4A8541', '#54A045', '#7ABF65', '#468937', '#2E6523',
        '#AEDB94', '#79C76A', '#3B722E', '#2C501E', '#56A04A',
        '#9BD88D', '#6FC95D', '#97D287', '#41922F', '#C0E8B3',
        '#7FC77D', '#1F5319', '#55A34E', '#93D281', '#3A802F',
        '#81C870', '#4F9E44', '#3D742D', '#6AB354', '#58A74C'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Card $card) {
            $card->color = $card->getRandomColor();
        });
    }

    public function getRandomColor()
    {
        $color = $this->colors[rand(0, count($this->colors) - 1)];

        $user = User::withTrashed()->find($this->user_id);

        $card = $user->cards()->where('color', $color)->first();

        if($card)
            return $this->getRandColor();

        return $color;
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
