<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Category extends Model implements HasMedia
{
    use HasFactory, SoftDeletes, InteractsWithMedia;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model){
            $prevModel = Category::orderBy("order", "desc")->first();

            if($model->category)
                $prevModel = $model->category->categories()->orderBy('order', 'desc')->first();

            $model->order = $prevModel ? $prevModel->order + 1 : 1;
        });
    }

    public function materials()
    {
        return $this->hasMany(Material::class);
    }
}
