<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model){
            $prevModel = City::orderBy('order', 'desc')->first();

            $model->order = $prevModel ? $prevModel->order + 1 : 1;
        });
    }

    public function counties()
    {
        return $this->hasMany(County::class);
    }
}
