<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    use HasFactory;

    protected $casts = [
        'will_finished_at' => 'date',
    ];

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model){
            $couponGroup = $model->couponGroup;

            $model->title = $couponGroup->title;
            $model->ratio_discount = $couponGroup->ratio_discount;
            $model->will_finished_at = Carbon::now()->addDays($couponGroup->durtion);
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function couponGroup()
    {
        return $this->belongsTo(CouponGroup::class);
    }

    public function order()
    {
        return $this->belongsTo(Order::class);
    }
}
