<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Delivery extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::deleted(function ($model){
            $user = User::withTrashed()->find($model->user_id);

            if($user->deliveries()->count() == 1)
                $user->deliveries()->first()->update(['main' => 1]);
        });

        self::updated(function ($model){
            $user = User::withTrashed()->find($model->user_id);

            $user->deliveries()->where('main', 1)->where('id', '!=', $model->id)->update(['main' => 0]);
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
