<?php

namespace App\Models;

use App\Enums\TypeAlarm;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Estimate extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function ($model){
            Alarm::create([
                'contact' => env('ADMIN_CONTACT', '01092106861'),
                'estimate_id' => $model->id,
                'type' => TypeAlarm::ESTIMATE_CREATED,
            ]);
        });
    }

    public function getFilesAttribute()
    {
        $medias = $this->getMedia("files");

        $items = [];

        foreach($medias as $media){
            $items[] = [
                "id" => $media->id,
                "name" => $media->file_name,
                "url" => $media->getFullUrl()
            ];
        }

        return $items;
    }
}
