<?php

namespace App\Models;

use App\Enums\StatePresetProduct;
use App\Enums\TypeAlarm;
use App\Mail\FeedbackCreated;
use App\Mail\PrototypeCreated;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Mail;

class Feedback extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function ($model){
            if(!$model->admin)
                Alarm::create([
                    'contact' => env('ADMIN_CONTACT', '01092106861'),
                    'type' => TypeAlarm::FEEDBACK_CREATED,
                    'feedback_id' => $model->id
                ]);

                // Mail::to(env('MAIL_ADMIN_ADDRESS', 'janginbiz@naver.com'))->send(new FeedbackCreated($model));
        });
    }

    protected $guarded = ['id'];

    public function presetProduct()
    {
        return $this->belongsTo(PresetProduct::class);
    }
}
