<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PackageSetting extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected $casts = [
        'will_order_at' => 'date',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (PackageSetting $packageSetting) {
            $packageSetting->name = $packageSetting->user->nickname."의 꾸러미";
        });

        self::updated(function (PackageSetting $packageSetting) {
            $prevActive = $packageSetting->getOriginal('active');

            if($prevActive && !$packageSetting->active)
                $packageSetting->stopHistories()->create();
        });
    }

    public function stopHistories()
    {
        return $this->hasMany(StopHistory::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function card(): BelongsTo
    {
        return $this->belongsTo(Card::class);
    }

    public function delivery(): BelongsTo
    {
        return $this->belongsTo(Delivery::class);
    }

    public function firstPackage(): BelongsTo
    {
        return $this->belongsTo(Package::class, 'first_package_id');
    }

    public function materials()
    {
        return $this->belongsToMany(Material::class, 'package_setting_material')->withPivot([
            'unlike'
        ]);
    }


}
