<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Package extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected $casts = [
        'will_delivery_at' => 'date',
        'start_pack_wait_at' => 'date',
        'finish_pack_wait_at' => 'date',
        'start_pack_at' => 'date',
        'finish_pack_at' => 'date',
        'start_delivery_ready_at' => 'date',
        'finish_delivery_ready_at' => 'date',
        'start_will_out_at' => 'date',
        'finish_will_out_at' => 'date',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (Package $package) {
            $prev = Package::orderBy('count', 'desc')->first();

            $package->count = $prev ? $prev->count + 1 : 1;
        });
    }

    public function materials()
    {
        return $this->belongsToMany(Material::class, 'package_material')->withPivot([
            'type',
            'count',
            'unit',
            'price_origin',
            'price'
        ]);
    }

    public function packageMaterials()
    {
        return $this->hasMany(PackageMaterial::class);
    }

    public function getPriceAttribute()
    {
        return $this->packageMaterials()->sum('price');
    }

    public static function getCurrent()
    {
        $packages = Package::where('will_delivery_at', '>=', Carbon::now()->startOfDay())
            ->orderBy('count', 'asc')
            ->cursor();

        $findPackage = null;

        foreach($packages as $package){
            // 도착예정일 2일전 오전 9시까지만 신규접수 받음
            $date = Carbon::make($package->will_delivery_at)->subDays(2)->setHour(9)->setMinutes(0)->setSeconds(0);

            if(Carbon::now() <= $date){
                $findPackage = $package;

                break;
            }
        }

        return $findPackage;
    }
}
