<?php

namespace App\Models;

use App\Enums\TypeDiscount;
use App\Enums\TypeOption;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class PresetProduct extends Model
{
    use HasFactory;

    protected $table = "preset_product";
    protected $guarded = ['id'];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function (PresetProduct $presetProduct) {
            $presetProduct = $presetProduct->calculatePrice();
        });

        self::updating(function (PresetProduct $presetProduct) {
            $presetProduct = $presetProduct->calculatePrice();
        });
    }

    public function preset(): BelongsTo
    {
        return $this->belongsTo(Preset::class);
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    public function option(): BelongsTo
    {
        return $this->belongsTo(Option::class);
    }

    public function coupon(): BelongsTo
    {
        return $this->belongsTo(Coupon::class);
    }

    public function calculatePrice()
    {
        $total = 0;

        $option = $this->option;

        if($option->type == TypeOption::REQUIRED) {
            $price = $this->option_price + $this->product_price;

            $total += $price * $this->count;
        }

        if($option->type == TypeOption::ADDITIONAL) {
            $price = $this->option_price;

            $total += $price * $this->count;
        }

        $this->products_price = $total;

        $this->price = $total - $this->price_coupon;

        return $this;
    }

    public function calculatePriceCoupon(Coupon $coupon)
    {
        $couponGroup = $coupon->couponGroup;

        $priceDiscount = 0;

        if($couponGroup->type_discount == TypeDiscount::NUMBER)
            $priceDiscount = $couponGroup->value;

        if($couponGroup->type_discount == TypeDiscount::RATIO)
            $priceDiscount = floor($this->price / 100 * $coupon->value);

        if($couponGroup->max_price_discount < $priceDiscount)
            $priceDiscount = $couponGroup->max_price_discount;

        return $priceDiscount;
    }
}
