<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model){
            $prevModel = Tag::where('type', $model->type)->orderBy('order', 'desc')->first();

            $model->order = $prevModel ? $prevModel->order + 1 : 1;
        });
    }
}
